/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 28
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON_COLON_EQ = 1,
  anon_sym_DOT = 2,
  sym_nonterminal = 3,
  sym_terminal = 4,
  anon_sym_PIPE = 5,
  anon_sym_SLASH = 6,
  anon_sym_LPAREN = 7,
  aux_sym_alias_token1 = 8,
  anon_sym_RPAREN = 9,
  sym_source_file = 10,
  sym__declaration = 11,
  sym_grammar_rule = 12,
  sym__nonterminal_m_alias = 13,
  sym__production = 14,
  sym__terminal_m_alias = 15,
  sym__multiterminal_m_alias = 16,
  sym_multiterminal = 17,
  sym_alias = 18,
  aux_sym_source_file_repeat1 = 19,
  aux_sym_grammar_rule_repeat1 = 20,
  aux_sym_multiterminal_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_COLON_EQ] = "::=",
  [anon_sym_DOT] = ".",
  [sym_nonterminal] = "nonterminal",
  [sym_terminal] = "terminal",
  [anon_sym_PIPE] = "|",
  [anon_sym_SLASH] = "/",
  [anon_sym_LPAREN] = "(",
  [aux_sym_alias_token1] = "alias_token1",
  [anon_sym_RPAREN] = ")",
  [sym_source_file] = "source_file",
  [sym__declaration] = "_declaration",
  [sym_grammar_rule] = "grammar_rule",
  [sym__nonterminal_m_alias] = "_nonterminal_m_alias",
  [sym__production] = "_production",
  [sym__terminal_m_alias] = "_terminal_m_alias",
  [sym__multiterminal_m_alias] = "_multiterminal_m_alias",
  [sym_multiterminal] = "multiterminal",
  [sym_alias] = "alias",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_grammar_rule_repeat1] = "grammar_rule_repeat1",
  [aux_sym_multiterminal_repeat1] = "multiterminal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_COLON_EQ] = anon_sym_COLON_COLON_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_nonterminal] = sym_nonterminal,
  [sym_terminal] = sym_terminal,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_alias_token1] = aux_sym_alias_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_source_file] = sym_source_file,
  [sym__declaration] = sym__declaration,
  [sym_grammar_rule] = sym_grammar_rule,
  [sym__nonterminal_m_alias] = sym__nonterminal_m_alias,
  [sym__production] = sym__production,
  [sym__terminal_m_alias] = sym__terminal_m_alias,
  [sym__multiterminal_m_alias] = sym__multiterminal_m_alias,
  [sym_multiterminal] = sym_multiterminal,
  [sym_alias] = sym_alias,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_grammar_rule_repeat1] = aux_sym_grammar_rule_repeat1,
  [aux_sym_multiterminal_repeat1] = aux_sym_multiterminal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_nonterminal] = {
    .visible = true,
    .named = true,
  },
  [sym_terminal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_alias_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__declaration] = {
    .visible = false,
    .named = true,
  },
  [sym_grammar_rule] = {
    .visible = true,
    .named = true,
  },
  [sym__nonterminal_m_alias] = {
    .visible = false,
    .named = true,
  },
  [sym__production] = {
    .visible = false,
    .named = true,
  },
  [sym__terminal_m_alias] = {
    .visible = false,
    .named = true,
  },
  [sym__multiterminal_m_alias] = {
    .visible = false,
    .named = true,
  },
  [sym_multiterminal] = {
    .visible = true,
    .named = true,
  },
  [sym_alias] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_grammar_rule_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiterminal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alias = 1,
  field_rule_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_rule_name] = "rule_name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 4},
  [5] = {.index = 9, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_rule_name, 0},
  [1] =
    {field_alias, 1},
    {field_rule_name, 0},
  [3] =
    {field_alias, 0, .inherited = true},
    {field_rule_name, 0, .inherited = true},
  [5] =
    {field_alias, 0, .inherited = true},
    {field_alias, 2, .inherited = true},
    {field_rule_name, 0, .inherited = true},
    {field_rule_name, 2, .inherited = true},
  [9] =
    {field_alias, 0, .inherited = true},
    {field_alias, 1, .inherited = true},
    {field_rule_name, 0, .inherited = true},
    {field_rule_name, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(14);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == '|') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == ':') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(6);
      END_STATE();
    case 3:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead == '|') ADVANCE(10);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(9);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON_COLON_EQ);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_nonterminal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_terminal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_alias_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 4},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 4},
  [4] = {.lex_state = 4},
  [5] = {.lex_state = 4},
  [6] = {.lex_state = 4},
  [7] = {.lex_state = 4},
  [8] = {.lex_state = 4},
  [9] = {.lex_state = 4},
  [10] = {.lex_state = 4},
  [11] = {.lex_state = 4},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 4},
  [14] = {.lex_state = 4},
  [15] = {.lex_state = 4},
  [16] = {.lex_state = 4},
  [17] = {.lex_state = 4},
  [18] = {.lex_state = 4},
  [19] = {.lex_state = 4},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON_COLON_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_nonterminal] = ACTIONS(1),
    [sym_terminal] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [aux_sym_alias_token1] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(23),
    [sym__declaration] = STATE(10),
    [sym_grammar_rule] = STATE(10),
    [sym__nonterminal_m_alias] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_nonterminal] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(5), 1,
      sym_nonterminal,
    ACTIONS(7), 1,
      anon_sym_DOT,
    ACTIONS(9), 1,
      sym_terminal,
    STATE(3), 1,
      aux_sym_grammar_rule_repeat1,
    STATE(12), 1,
      sym_multiterminal,
    STATE(15), 1,
      sym__nonterminal_m_alias,
    STATE(16), 1,
      sym__terminal_m_alias,
    STATE(18), 1,
      sym__multiterminal_m_alias,
    STATE(20), 1,
      sym__production,
  [28] = 9,
    ACTIONS(5), 1,
      sym_nonterminal,
    ACTIONS(9), 1,
      sym_terminal,
    ACTIONS(11), 1,
      anon_sym_DOT,
    STATE(4), 1,
      aux_sym_grammar_rule_repeat1,
    STATE(12), 1,
      sym_multiterminal,
    STATE(15), 1,
      sym__nonterminal_m_alias,
    STATE(16), 1,
      sym__terminal_m_alias,
    STATE(18), 1,
      sym__multiterminal_m_alias,
    STATE(20), 1,
      sym__production,
  [56] = 9,
    ACTIONS(13), 1,
      anon_sym_DOT,
    ACTIONS(15), 1,
      sym_nonterminal,
    ACTIONS(18), 1,
      sym_terminal,
    STATE(4), 1,
      aux_sym_grammar_rule_repeat1,
    STATE(12), 1,
      sym_multiterminal,
    STATE(15), 1,
      sym__nonterminal_m_alias,
    STATE(16), 1,
      sym__terminal_m_alias,
    STATE(18), 1,
      sym__multiterminal_m_alias,
    STATE(20), 1,
      sym__production,
  [84] = 5,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(6), 1,
      aux_sym_multiterminal_repeat1,
    STATE(17), 1,
      sym_alias,
    ACTIONS(23), 2,
      anon_sym_PIPE,
      anon_sym_SLASH,
    ACTIONS(21), 3,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [103] = 3,
    STATE(7), 1,
      aux_sym_multiterminal_repeat1,
    ACTIONS(23), 2,
      anon_sym_PIPE,
      anon_sym_SLASH,
    ACTIONS(27), 4,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
      anon_sym_LPAREN,
  [117] = 3,
    STATE(7), 1,
      aux_sym_multiterminal_repeat1,
    ACTIONS(31), 2,
      anon_sym_PIPE,
      anon_sym_SLASH,
    ACTIONS(29), 4,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
      anon_sym_LPAREN,
  [131] = 3,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(13), 1,
      sym_alias,
    ACTIONS(34), 4,
      anon_sym_COLON_COLON_EQ,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [144] = 4,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    ACTIONS(38), 1,
      sym_nonterminal,
    STATE(26), 1,
      sym__nonterminal_m_alias,
    STATE(9), 3,
      sym__declaration,
      sym_grammar_rule,
      aux_sym_source_file_repeat1,
  [159] = 4,
    ACTIONS(5), 1,
      sym_nonterminal,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      sym__nonterminal_m_alias,
    STATE(9), 3,
      sym__declaration,
      sym_grammar_rule,
      aux_sym_source_file_repeat1,
  [174] = 1,
    ACTIONS(29), 6,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
      anon_sym_PIPE,
      anon_sym_SLASH,
      anon_sym_LPAREN,
  [183] = 3,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    STATE(19), 1,
      sym_alias,
    ACTIONS(43), 3,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [195] = 1,
    ACTIONS(45), 4,
      anon_sym_COLON_COLON_EQ,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [202] = 1,
    ACTIONS(47), 4,
      anon_sym_COLON_COLON_EQ,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [209] = 1,
    ACTIONS(49), 3,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [215] = 1,
    ACTIONS(49), 3,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [221] = 1,
    ACTIONS(51), 3,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [227] = 1,
    ACTIONS(49), 3,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [233] = 1,
    ACTIONS(53), 3,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [239] = 1,
    ACTIONS(55), 3,
      anon_sym_DOT,
      sym_nonterminal,
      sym_terminal,
  [245] = 1,
    ACTIONS(57), 2,
      ts_builtin_sym_end,
      sym_nonterminal,
  [250] = 1,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      sym_nonterminal,
  [255] = 1,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
  [259] = 1,
    ACTIONS(63), 1,
      anon_sym_RPAREN,
  [263] = 1,
    ACTIONS(65), 1,
      aux_sym_alias_token1,
  [267] = 1,
    ACTIONS(67), 1,
      anon_sym_COLON_COLON_EQ,
  [271] = 1,
    ACTIONS(69), 1,
      sym_terminal,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 103,
  [SMALL_STATE(7)] = 117,
  [SMALL_STATE(8)] = 131,
  [SMALL_STATE(9)] = 144,
  [SMALL_STATE(10)] = 159,
  [SMALL_STATE(11)] = 174,
  [SMALL_STATE(12)] = 183,
  [SMALL_STATE(13)] = 195,
  [SMALL_STATE(14)] = 202,
  [SMALL_STATE(15)] = 209,
  [SMALL_STATE(16)] = 215,
  [SMALL_STATE(17)] = 221,
  [SMALL_STATE(18)] = 227,
  [SMALL_STATE(19)] = 233,
  [SMALL_STATE(20)] = 239,
  [SMALL_STATE(21)] = 245,
  [SMALL_STATE(22)] = 250,
  [SMALL_STATE(23)] = 255,
  [SMALL_STATE(24)] = 259,
  [SMALL_STATE(25)] = 263,
  [SMALL_STATE(26)] = 267,
  [SMALL_STATE(27)] = 271,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grammar_rule_repeat1, 2, 0, 5),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grammar_rule_repeat1, 2, 0, 5), SHIFT_REPEAT(8),
  [18] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_grammar_rule_repeat1, 2, 0, 5), SHIFT_REPEAT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__terminal_m_alias, 1, 0, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiterminal, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_multiterminal_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_multiterminal_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__nonterminal_m_alias, 1, 0, 1),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiterminal_m_alias, 1, 0, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__nonterminal_m_alias, 2, 0, 2),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_alias, 3, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__production, 1, 0, 3),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__terminal_m_alias, 2, 0, 2),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiterminal_m_alias, 2, 0, 2),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_grammar_rule_repeat1, 1, 0, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar_rule, 3, 0, 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grammar_rule, 4, 0, 4),
  [61] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_zitron(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "zitron",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
